name: Clean Design Tokens

on:
  push:
    paths:
      - "tokens/tokens.json"

jobs:
  clean:
    if: github.actor != 'github-actions'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run cleaner
        run: node scripts/git-tokens/tokens-clean.js

      - name: Commit cleaned tokens
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add clean-tokens.json
          git commit -m "chore: clean tokens" || echo "No changes"
          git push
